// Inlines everything in public/ into a single Worker module at dist/worker.js.
// The site is a handful of small files, so embedding them beats a separate asset
// store: one artifact to deploy, no cold lookups, and `npm run deploy` reproduces
// byte-for-byte whatever is currently in public/. The Worker also handles the
// order form, which is the one dynamic thing on the site.
import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { join, extname } from "node:path";

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".json": "application/json; charset=utf-8",
};
const TEXTUAL = new Set([".html", ".svg", ".txt", ".xml", ".json"]);

const root = new URL("./public/", import.meta.url);
const names = (await readdir(root)).sort();

const files = {};
for (const name of names) {
  const ext = extname(name).toLowerCase();
  const type = TYPES[ext];
  if (!type) throw new Error(`No content type mapped for ${name}`);

  const bytes = await readFile(join(root.pathname, name));
  const etag = `"${createHash("sha256").update(bytes).digest("hex").slice(0, 16)}"`;
  const textual = TEXTUAL.has(ext);

  files["/" + name] = {
    body: textual ? bytes.toString("utf8") : bytes.toString("base64"),
    b64: !textual,
    type,
    etag,
    // Content is unhashed, so revalidate HTML every time and let the rest sit
    // in cache for an hour.
    cache: ext === ".html"
      ? "public, max-age=0, must-revalidate"
      : "public, max-age=3600",
  };
  console.log(`  ${name.padEnd(14)} ${String(bytes.length).padStart(7)} bytes`);
}

if (!files["/index.html"]) throw new Error("public/index.html is required");

const worker = `// Generated by build.mjs - do not edit. Edit public/ instead.
const FILES = ${JSON.stringify(files, null, 2)};

const SECURITY_HEADERS = {
  "x-content-type-options": "nosniff",
  "referrer-policy": "strict-origin-when-cross-origin",
  "x-frame-options": "SAMEORIGIN",
};

const PLANS = {
  bench: "Bench - $299/month + $6/bench-hour",
  rack: "Rack - $1,200/month + $4/bench-hour",
  dedicated: "Dedicated lab - quote requested",
};

// Orders are the one thing on this site we cannot afford to drop, so a bad
// forward is logged loudly rather than swallowed, and the customer still gets
// their confirmation page either way.
async function placeOrder(request, env) {
  let form;
  try {
    form = await request.formData();
  } catch {
    return new Response("Could not read the order form.", {
      status: 400,
      headers: { "content-type": "text/plain; charset=utf-8", ...SECURITY_HEADERS },
    });
  }

  const field = (name, max) => String(form.get(name) ?? "").trim().slice(0, max);

  // Honeypot: a real person never sees this input, so anything in it is a bot.
  // Answer as if the order went through rather than telling the bot it failed.
  if (field("fax", 80)) return Response.redirect(new URL("/order-received", request.url).toString(), 303);

  const order = {
    plan: field("plan", 40),
    name: field("name", 120),
    email: field("email", 200),
    company: field("company", 160),
    benches: field("benches", 4),
    hardware: field("hardware", 2000),
  };

  const invalid =
    !PLANS[order.plan] ||
    !order.name ||
    !order.company ||
    !/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(order.email);

  if (invalid) {
    return new Response("That order is missing a plan, name, company or valid email address. Please go back and try again.", {
      status: 400,
      headers: { "content-type": "text/plain; charset=utf-8", ...SECURITY_HEADERS },
    });
  }

  const record = {
    ...order,
    planLabel: PLANS[order.plan],
    receivedAt: new Date().toISOString(),
    country: request.headers.get("cf-ipcountry") ?? null,
  };

  // Always log it: the log is the backstop if the webhook is unset or down.
  console.log("ORDER " + JSON.stringify(record));

  if (env && env.ORDER_WEBHOOK_URL) {
    try {
      const res = await fetch(env.ORDER_WEBHOOK_URL, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(record),
      });
      if (!res.ok) console.error("ORDER_FORWARD_FAILED status=" + res.status);
    } catch (err) {
      console.error("ORDER_FORWARD_ERROR " + String(err));
    }
  } else {
    console.error("ORDER_WEBHOOK_URL is not set - order exists only in this log");
  }

  return Response.redirect(new URL("/order-received", request.url).toString(), 303);
}

function decode(file) {
  if (!file.b64) return file.body;
  const bin = atob(file.body);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

export default {
  fetch(request, env) {
    const url = new URL(request.url);

    // One canonical hostname, so the canonical tag and the URL agree.
    if (url.hostname === "www.hardstack.com") {
      url.hostname = "hardstack.com";
      return Response.redirect(url.toString(), 301);
    }

    if (url.pathname === "/order" && request.method === "POST") {
      return placeOrder(request, env);
    }

    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", {
        status: 405,
        headers: { allow: "GET, HEAD", ...SECURITY_HEADERS },
      });
    }

    let path = url.pathname;
    if (path === "/" || path === "/index.html") path = "/index.html";
    else if (path.length > 1 && path.endsWith("/")) path = path.slice(0, -1);

    // Pretty URLs: /order-received serves order-received.html.
    if (!FILES[path] && !path.includes(".") && FILES[path + ".html"]) path += ".html";

    // A GET to /order means someone reloaded or bookmarked the form target;
    // send them to the form rather than a 404.
    if (path === "/order") {
      return Response.redirect(new URL("/#order", url).toString(), 303);
    }

    const file = FILES[path];
    if (!file) {
      return new Response("Not found", {
        status: 404,
        headers: { "content-type": "text/plain; charset=utf-8", ...SECURITY_HEADERS },
      });
    }

    const headers = {
      "content-type": file.type,
      "cache-control": file.cache,
      etag: file.etag,
      ...SECURITY_HEADERS,
    };

    if (request.headers.get("if-none-match") === file.etag) {
      return new Response(null, { status: 304, headers });
    }

    return new Response(request.method === "HEAD" ? null : decode(file), { headers });
  },
};
`;

await mkdir(new URL("./dist/", import.meta.url), { recursive: true });
await writeFile(new URL("./dist/worker.js", import.meta.url), worker);
console.log(`\ndist/worker.js  ${worker.length} bytes`);
